services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    volumes:
      - .:/src
    environment:
      NODE_ENV: development
    stdin_open: true 
    command: npm run dev